title: "My Awesome GitHub Page"  # 你的主页标题
description: "Welcome to my personal website!"  # 网站的描述，可以修改为你想要的
theme: jekyll-theme-cayman  # 你选择的主题，可以根据需要更改
baseurl: ""  # 如果是一个个人主页，保持为空；如果是项目页面，设置为"/your-repo-name"
url: "https://github.com/XuNing525"  # 你 GitHub 主页的 URL。将 "your-username" 替换为你的 GitHub 用户名
markdown: kramdown  # 使用 kramdown 作为 Markdown 渲染引擎，默认设置

